In [1]:
import pandas as pd

data = {
    "Name": ["Bhakti", "Apeksha", None, "Priya", "Sneha", "Rahul"],
    "Age": [22, None, 21, 23, None, 24],
    "Subject": ["Python", "Java", "SQL", None, "Python", "Excel"],
    "Marks": [85, 90, None, 76, 88, 90],
    "Salary": [7000, 8000, 9000, None, 7000, 10000],
    "Mock_Rating": [1.5, None, 2.0, 1.0, None, 2.5],
    "Date_Time": [
        "22-10-2026 16:21",
        "21-10-2026 10:30",
        "20-09-2025 14:45",
        None,
        "15-08-2026 09:15",
        "10-07-2025 11:50"
    ]
}

df = pd.DataFrame(data)

print(df)

      Name   Age Subject  Marks   Salary  Mock_Rating         Date_Time
0   Bhakti  22.0  Python   85.0   7000.0          1.5  22-10-2026 16:21
1  Apeksha   NaN    Java   90.0   8000.0          NaN  21-10-2026 10:30
2      NaN  21.0     SQL    NaN   9000.0          2.0  20-09-2025 14:45
3    Priya  23.0     NaN   76.0      NaN          1.0               NaN
4    Sneha   NaN  Python   88.0   7000.0          NaN  15-08-2026 09:15
5    Rahul  24.0   Excel   90.0  10000.0          2.5  10-07-2025 11:50

In [3]:

#find number of rows and columns in dataframe:-> use Shape

df.shape

(6, 7)

In [4]:
#find total number of elements
df.size

42

In [5]:
df.ndim

2

In [6]:
df.columns

Index(['Name', 'Age', 'Subject', 'Marks', 'Salary', 'Mock_Rating',
       'Date_Time'],
      dtype='str')

In [7]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [8]:
df

      Name   Age Subject  Marks   Salary  Mock_Rating         Date_Time
0   Bhakti  22.0  Python   85.0   7000.0          1.5  22-10-2026 16:21
1  Apeksha   NaN    Java   90.0   8000.0          NaN  21-10-2026 10:30
2      NaN  21.0     SQL    NaN   9000.0          2.0  20-09-2025 14:45
3    Priya  23.0     NaN   76.0      NaN          1.0               NaN
4    Sneha   NaN  Python   88.0   7000.0          NaN  15-08-2026 09:15
5    Rahul  24.0   Excel   90.0  10000.0          2.5  10-07-2025 11:50

In [9]:
df.fillna("*")

      Name   Age Subject Marks   Salary Mock_Rating         Date_Time
0   Bhakti  22.0  Python  85.0   7000.0         1.5  22-10-2026 16:21
1  Apeksha     *    Java  90.0   8000.0           *  21-10-2026 10:30
2        *  21.0     SQL     *   9000.0         2.0  20-09-2025 14:45
3    Priya  23.0       *  76.0        *         1.0                 *
4    Sneha     *  Python  88.0   7000.0           *  15-08-2026 09:15
5    Rahul  24.0   Excel  90.0  10000.0         2.5  10-07-2025 11:50

In [10]:
df.ffill()

      Name   Age Subject  Marks   Salary  Mock_Rating         Date_Time
0   Bhakti  22.0  Python   85.0   7000.0          1.5  22-10-2026 16:21
1  Apeksha  22.0    Java   90.0   8000.0          1.5  21-10-2026 10:30
2  Apeksha  21.0     SQL   90.0   9000.0          2.0  20-09-2025 14:45
3    Priya  23.0     SQL   76.0   9000.0          1.0  20-09-2025 14:45
4    Sneha  23.0  Python   88.0   7000.0          1.0  15-08-2026 09:15
5    Rahul  24.0   Excel   90.0  10000.0          2.5  10-07-2025 11:50

In [11]:
df.bfill()

      Name   Age Subject  Marks   Salary  Mock_Rating         Date_Time
0   Bhakti  22.0  Python   85.0   7000.0          1.5  22-10-2026 16:21
1  Apeksha  21.0    Java   90.0   8000.0          2.0  21-10-2026 10:30
2    Priya  21.0     SQL   76.0   9000.0          2.0  20-09-2025 14:45
3    Priya  23.0  Python   76.0   7000.0          1.0  15-08-2026 09:15
4    Sneha  24.0  Python   88.0   7000.0          2.5  15-08-2026 09:15
5    Rahul  24.0   Excel   90.0  10000.0          2.5  10-07-2025 11:50

In [13]:

#insert one column

df["Add"]="-"
df

      Name   Age Subject  Marks   Salary  Mock_Rating         Date_Time Add
0   Bhakti  22.0  Python   85.0   7000.0          1.5  22-10-2026 16:21   -
1  Apeksha   NaN    Java   90.0   8000.0          NaN  21-10-2026 10:30   -
2      NaN  21.0     SQL    NaN   9000.0          2.0  20-09-2025 14:45   -
3    Priya  23.0     NaN   76.0      NaN          1.0               NaN   -
4    Sneha   NaN  Python   88.0   7000.0          NaN  15-08-2026 09:15   -
5    Rahul  24.0   Excel   90.0  10000.0          2.5  10-07-2025 11:50   -

In [17]:
#add multiple column using assign

df.assign(a=["*","*","*","*","*","*"],b=["%","%","%","%","%","%"])

,Name,Age,Subject,Marks,Salary,Mock_Rating,Date_Time,Add,a,b
0,Bhakti,22.0,Python,85.0,7000.0,1.5,22-10-2026 16:21,-,*,%
1,Apeksha,NaN,Java,90.0,8000.0,NaN,21-10-2026 10:30,-,*,%
2,NaN,21.0,SQL,NaN,9000.0,2.0,20-09-2025 14:45,-,*,%
3,Priya,23.0,NaN,76.0,NaN,1.0,NaN,-,*,%
4,Sneha,NaN,Python,88.0,7000.0,NaN,15-08-2026 09:15,-,*,%
5,Rahul,24.0,Excel,90.0,10000.0,2.5,10-07-2025 11:50,-,*,%

In [20]:
#Add column in between 

df.insert(2,'X',[10,20,30,40,50,60])
df

,Name,Age,X,C,Subject,Marks,Salary,Mock_Rating,Date_Time,Add
0,Bhakti,22.0,10,10,Python,85.0,7000.0,1.5,22-10-2026 16:21,-
1,Apeksha,NaN,20,20,Java,90.0,8000.0,NaN,21-10-2026 10:30,-
2,NaN,21.0,30,30,SQL,NaN,9000.0,2.0,20-09-2025 14:45,-
3,Priya,23.0,40,40,NaN,76.0,NaN,1.0,NaN,-
4,Sneha,NaN,50,50,Python,88.0,7000.0,NaN,15-08-2026 09:15,-
5,Rahul,24.0,60,60,Excel,90.0,10000.0,2.5,10-07-2025 11:50,-

In [21]:
# i want to create sepearate date time day , month

df['Date_Time']=pd.to_datetime(df['Date_Time'])

C:\Users\Bhakti\AppData\Local\Temp\ipykernel_37160\3457903215.py:3: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Date_Time']=pd.to_datetime(df['Date_Time'])

In [22]:
df

,Name,Age,X,C,Subject,Marks,Salary,Mock_Rating,Date_Time,Add
0,Bhakti,22.0,10,10,Python,85.0,7000.0,1.5,2026-10-22 16:21:00,-
1,Apeksha,NaN,20,20,Java,90.0,8000.0,NaN,2026-10-21 10:30:00,-
2,NaN,21.0,30,30,SQL,NaN,9000.0,2.0,2025-09-20 14:45:00,-
3,Priya,23.0,40,40,NaN,76.0,NaN,1.0,NaT,-
4,Sneha,NaN,50,50,Python,88.0,7000.0,NaN,2026-08-15 09:15:00,-
5,Rahul,24.0,60,60,Excel,90.0,10000.0,2.5,2025-07-10 11:50:00,-

In [ ]:
df['Month']=pd.to_datetime(df['Date_Time']).dt.month
df

TypeError: <class 'method'> is not convertible to datetime