In [ ]:
'''DataFrame:-> DataFrame is combination of row and column , 
DataFrame is 2D dimension data structure, it is like tabular strutucre
'''

In [2]:
#creating a data frame

import pandas as pd

data={
    "Name":["bhakti","apeksha"],
    "age":[22,23],
    "sub":["Java ","Python"]
}

df=pd.DataFrame(data)

print(df)

      Name  age     sub
0   bhakti   22   Java
1  apeksha   23  Python

In [3]:
name=["A",None,"B","None"]

age=[None,23,None,45]
sal=[7000,None,8000,None]

data={"Name":name,"Age":age,"Sal":sal}

df=pd.DataFrame(data)
print(df)

   Name   Age     Sal
0     A   NaN  7000.0
1   NaN  23.0     NaN
2     B   NaN  8000.0
3  None  45.0     NaN

In [ ]:
df.fillna("*") #replace none values only temporerily

   Name   Age     Sal
0     A     *  7000.0
1     *  23.0       *
2     B     *  8000.0
3  None  45.0       *

In [5]:
#forward fill :ffill :-> top -> bottom
df.ffill()

   Name   Age     Sal
0     A   NaN  7000.0
1     A  23.0  7000.0
2     B  23.0  8000.0
3  None  45.0  8000.0

In [6]:
#backward fill: bfill:-> bottom -> top 
df.bfill()

   Name   Age     Sal
0     A  23.0  7000.0
1     B  23.0  8000.0
2     B  45.0  8000.0
3  None  45.0     NaN

In [ ]:
#rename the column name  syntax:-> varname.rename(columns={key:value})
df.rename(columns={"Sal":"Salary"})

   Name   Age  Salary
0     A   NaN  7000.0
1   NaN  23.0     NaN
2     B   NaN  8000.0
3  None  45.0     NaN

In [9]:
#rename mulitple column name
df.rename(columns={"Sal":"Salary","Age":"A*e","Name":"FullName"})

  FullName   A*e  Salary
0        A   NaN  7000.0
1      NaN  23.0     NaN
2        B   NaN  8000.0
3     None  45.0     NaN

In [12]:
#delete sal column
df.drop("Sal")

KeyError: "['Sal'] not found in axis"

In [ ]:
'''if we want to delete column then mandatory to provide axis :-> col axies:1, row axis:0  
_> if i want to delte permentaly then [inplace=True] otherwise it will delete temporery'''

In [13]:
df.drop("Sal",axis=1)

   Name   Age
0     A   NaN
1   NaN  23.0
2     B   NaN
3  None  45.0

In [15]:
#If i want to delete row
df.drop(2,axis=0)

   Name   Age     Sal
0     A   NaN  7000.0
1   NaN  23.0     NaN
3  None  45.0     NaN

In [17]:
import pandas as pd

df=pd.DataFrame({"SUB":["PY","WEB","JAVA"],"MOCK_RATING":["*",1,1.5]})

print(df)

    SUB MOCK_RATING
0    PY           *
1   WEB           1
2  JAVA         1.5

In [20]:
#If i want to add one extra row
#we can use then 

df.loc[3]=["Excel",1.5]

df.loc[4]=["powerbi","*"]
print(df)

       SUB MOCK_RATING
0       PY           *
1      WEB           1
2     JAVA         1.5
3    Excel         1.5
4  powerbi           *

In [21]:
#in java subject ka mock_rating update karna h 

df.loc[2,"MOCK_RATING"]=1
print(df)

       SUB MOCK_RATING
0       PY           *
1      WEB           1
2     JAVA           1
3    Excel         1.5
4  powerbi           *

In [ ]:
#i want to add new column 
#1. without using inbuilt function :-> varname["new_colName"]=default value
#if i want to add mulitple columne :-> we can go inbuilt function :=> 
#2. assign:-> varname.assign(c1=[values],c2=[values])

df

       SUB MOCK_RATING
0       PY           *
1      WEB           1
2     JAVA           1
3    Excel         1.5
4  powerbi           *

In [27]:
#Add total_marks col

df["TOTAL_MARKS"]=10

df

       SUB MOCK_RATING  TOTAL_MARKS
0       PY           *           10
1      WEB           1           10
2     JAVA           1           10
3    Excel         1.5           10
4  powerbi           *           10

In [ ]:
#Add multiple columns :-> assign into new varable
x=df.assign(c1=[11,22,33,44,55],c2=["a","b","c","d","e"])

In [32]:
x

       SUB MOCK_RATING  TOTAL_MARKS  c1 c2
0       PY           *           10  11  a
1      WEB           1           10  22  b
2     JAVA           1           10  33  c
3    Excel         1.5           10  44  d
4  powerbi           *           10  55  e

In [ ]:
#I want to insert in between two column :-> syntax 
# varname.insert(indexPositon,colname,[values])
df
#if i want to add after sub i want grad col :-> and 5 values

       SUB MOCK_RATING  TOTAL_MARKS
0       PY           *           10
1      WEB           1           10
2     JAVA           1           10
3    Excel         1.5           10
4  powerbi           *           10

In [ ]:
#add column in between two col:-> varname.insert(index,colname,[values])
df.insert(1,"Grade",["S","S1","F","B","A"])
df

       SUB Grade MOCK_RATING  TOTAL_MARKS
0       PY     S           *           10
1      WEB    S1           1           10
2     JAVA     F           1           10
3    Excel     B         1.5           10
4  powerbi     A           *           10

In [ ]:

import pandas as pd

date_time=["22-10-2026 16:21","21-10-2026 4:23","17-09-2025 10:30"]

df=pd.DataFrame({"Date_Time":date_time})

df

          Date_Time
0  22-10-2026 16:21
1   21-10-2026 4:23
2  17-09-2025 10:30

In [ ]:
#now  i want to create sepearate date / month/year / time 

#i want to fetch spearte separate use :-> to_datetime function:->  

#Permenat changes will be done after updating 

df['Date_Time']=pd.to_datetime(df['Date_Time'])

C:\Users\Bhakti\AppData\Local\Temp\ipykernel_11656\395205800.py:5: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Date_Time']=pd.to_datetime(df['Date_Time'])

In [38]:
#Create a year col 
df['Year']=pd.to_datetime(df['Date_Time']).dt.year #dt is inbuilt function

df

            Date_Time  Year
0 2026-10-22 16:21:00  2026
1 2026-10-21 04:23:00  2026
2 2025-09-17 10:30:00  2025

In [39]:
#create a month col
df['Month']=pd.to_datetime(df['Date_Time']).dt.month
df

            Date_Time  Year  Month
0 2026-10-22 16:21:00  2026     10
1 2026-10-21 04:23:00  2026     10
2 2025-09-17 10:30:00  2025      9

In [41]:
#create a day
df['Day']=df['Date_Time'].dt.day
df

            Date_Time  Year  Month  Day
0 2026-10-22 16:21:00  2026     10   22
1 2026-10-21 04:23:00  2026     10   21
2 2025-09-17 10:30:00  2025      9   17

In [43]:
#create a month name col
df['Month_name ']=df['Date_Time'].dt.month_name()
df

            Date_Time  Year  Month  Day Month_name
0 2026-10-22 16:21:00  2026     10   22     October
1 2026-10-21 04:23:00  2026     10   21     October
2 2025-09-17 10:30:00  2025      9   17   September

In [44]:
#create a hour col
df['Hour']=df['Date_Time'].dt.hour
df

            Date_Time  Year  Month  Day Month_name   Hour
0 2026-10-22 16:21:00  2026     10   22     October    16
1 2026-10-21 04:23:00  2026     10   21     October     4
2 2025-09-17 10:30:00  2025      9   17   September    10

In [45]:
#create a minute col
df["Minute"]=df['Date_Time'].dt.minute
df

            Date_Time  Year  Month  Day Month_name   Hour  Minute
0 2026-10-22 16:21:00  2026     10   22     October    16      21
1 2026-10-21 04:23:00  2026     10   21     October     4      23
2 2025-09-17 10:30:00  2025      9   17   September    10      30

In [46]:
#create day name col
df["DayName"]=df['Date_Time'].dt.day_name()
df

            Date_Time  Year  Month  Day Month_name   Hour  Minute    DayName
0 2026-10-22 16:21:00  2026     10   22     October    16      21   Thursday
1 2026-10-21 04:23:00  2026     10   21     October     4      23  Wednesday
2 2025-09-17 10:30:00  2025      9   17   September    10      30  Wednesday

In [48]:
#create second col
df["Second"]=df['Date_Time'].dt.second
df

,Date_Time,Year,Month,Day,Month_name,Hour,Minute,DayName,Second
0,2026-10-22 16:21:00,2026,10,22,October,16,21,Thursday,0
1,2026-10-21 04:23:00,2026,10,21,October,4,23,Wednesday,0
2,2025-09-17 10:30:00,2025,9,17,September,10,30,Wednesday,0

In [50]:
#create weekday col
df['Week_Day']=df['Date_Time'].dt.day_of_week
df

,Date_Time,Year,Month,Day,Month_name,Hour,Minute,DayName,Second,Week_Day
0,2026-10-22 16:21:00,2026,10,22,October,16,21,Thursday,0,3
1,2026-10-21 04:23:00,2026,10,21,October,4,23,Wednesday,0,2
2,2025-09-17 10:30:00,2025,9,17,September,10,30,Wednesday,0,2

In [52]:

name=["A","B","C","D"]

age=[25,23,30,45]
sal=[7000,10000,8000,9000]

data={"Name":name,"Age":age,"Sal":sal}

df=pd.DataFrame(data)
print(df)

  Name  Age    Sal
0    A   25   7000
1    B   23  10000
2    C   30   8000
3    D   45   9000

In [ ]:
#perform aggregation function
'''1. min
2.max
3.sum

df["Sal"].agg(["max", "min", "count", "sum"])

'''

In [53]:
df.min()

Name       A
Age       23
Sal     7000
dtype: object

In [54]:
df.max()

Name        D
Age        45
Sal     10000
dtype: object

In [61]:
df["Sal"].agg(["max", "min", "count", "sum"])

max      10000
min       7000
count        4
sum      34000
Name: Sal, dtype: int64

In [68]:
df

  Name  Age    Sal  Operations
0    A   25   7000         NaN
1    B   23  10000         NaN
2    C   30   8000         NaN
3    D   45   9000         NaN

In [70]:
x=df.replace({7000:8000,9000:160000})
x

  Name  Age     Sal  Operations
0    A   25    8000         NaN
1    B   23   10000         NaN
2    C   30    8000         NaN
3    D   45  160000         NaN