In [ ]:
'''1. Rank method:-> start from 1
        Syntax:-> varname.rank #s.rank

        -> smaller number 1st rank

        -> rank method by default mean

        -> in rank :-> method:-> 5 argument
        1. average
        2. dense :-> you have duplicated mens first ele postion will be display
        3. max
        4. min
        5. first
        
'''

In [1]:
import pandas as pd

z=pd.Series([45,35,78,90,85,75])

print(z)

0    45
1    35
2    78
3    90
4    85
5    75
dtype: int64

In [2]:
z.rank()

0    2.0
1    1.0
2    4.0
3    6.0
4    5.0
5    3.0
dtype: float64

In [ ]:
z.rank(ascending=False) #85,90,75,35,45,78

0    5.0
1    6.0
2    3.0
3    1.0
4    2.0
5    4.0
dtype: float64

In [ ]:
x=pd.Series([78,90,85,65,45,23])
#            4, 6 ,5 ,3, 2, 1
x

0    78
1    90
2    85
3    65
4    45
5    23
dtype: int64

In [7]:
x.rank()

0    4.0
1    6.0
2    5.0
3    3.0
4    2.0
5    1.0
dtype: float64

In [ ]:
x.rank(ascending=False) #65,23,45,78,85,90

0    3.0
1    1.0
2    2.0
3    4.0
4    5.0
5    6.0
dtype: float64

In [9]:
s=pd.Series([55,75,83,83,90,95])
s

0    55
1    75
2    83
3    83
4    90
5    95
dtype: int64

In [10]:
s.rank(method='average')

0    1.0
1    2.0
2    3.5
3    3.5
4    5.0
5    6.0
dtype: float64

In [11]:
s.rank(method='max')

0    1.0
1    2.0
2    4.0
3    4.0
4    5.0
5    6.0
dtype: float64

In [13]:
s.rank(method='min')

0    1.0
1    2.0
2    3.0
3    3.0
4    5.0
5    6.0
dtype: float64

In [ ]:
s.rank(method='dense') #whenver we use it will give output as it is

0    1.0
1    2.0
2    3.0
3    3.0
4    4.0
5    5.0
dtype: float64

In [ ]:
s.rank(method='first')#whenver we applying first then first come first serve

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
dtype: float64

In [ ]:
q=pd.Series([45,56,56,63,56,98]) #1,2,3,4,5,6
q

0    45
1    56
2    56
3    63
4    56
5    98
dtype: int64

In [17]:
q.rank(method='average')

0    1.0
1    3.0
2    3.0
3    5.0
4    3.0
5    6.0
dtype: float64

In [18]:
q.rank(method="dense")

0    1.0
1    2.0
2    2.0
3    3.0
4    2.0
5    4.0
dtype: float64

In [19]:


#using data frane

name=["Ravi","kiran","ram","naveen","krisha"]
marks=[50,70,89,90,90]
data={"NAME": name,"MARKS":marks}

df=pd.DataFrame(data)
df

     NAME  MARKS
0    Ravi     50
1   kiran     70
2     ram     89
3  naveen     90
4  krisha     90

In [21]:
#
df["Rank"]=df["MARKS"].rank()
df

     NAME  MARKS  Rank
0    Ravi     50   1.0
1   kiran     70   2.0
2     ram     89   3.0
3  naveen     90   4.5
4  krisha     90   4.5

In [25]:
df["MAX"]=df["MARKS"].rank(method='max')
df

     NAME  MARKS  Rank  MAX
0    Ravi     50   1.0  1.0
1   kiran     70   2.0  2.0
2     ram     89   3.0  3.0
3  naveen     90   5.0  5.0
4  krisha     90   5.0  5.0

In [27]:
df["MIN"]=df["MARKS"].rank(method='min')
df

     NAME  MARKS  Rank  MAX  MIN
0    Ravi     50   1.0  1.0  1.0
1   kiran     70   2.0  2.0  2.0
2     ram     89   3.0  3.0  3.0
3  naveen     90   5.0  5.0  4.0
4  krisha     90   5.0  5.0  4.0

In [28]:
df["DENSE"]=df["MARKS"].rank(method='dense')
df

     NAME  MARKS  Rank  MAX  MIN  DENSE
0    Ravi     50   1.0  1.0  1.0    1.0
1   kiran     70   2.0  2.0  2.0    2.0
2     ram     89   3.0  3.0  3.0    3.0
3  naveen     90   5.0  5.0  4.0    4.0
4  krisha     90   5.0  5.0  4.0    4.0

In [29]:
df["FIRST"]=df["MARKS"].rank(method='first')
df

     NAME  MARKS  Rank  MAX  MIN  DENSE  FIRST
0    Ravi     50   1.0  1.0  1.0    1.0    1.0
1   kiran     70   2.0  2.0  2.0    2.0    2.0
2     ram     89   3.0  3.0  3.0    3.0    3.0
3  naveen     90   5.0  5.0  4.0    4.0    4.0
4  krisha     90   5.0  5.0  4.0    4.0    5.0

In [30]:
df["AVERAGE"]=df["MARKS"].rank(method='average')
df

     NAME  MARKS  Rank  MAX  MIN  DENSE  FIRST  AVERAGE
0    Ravi     50   1.0  1.0  1.0    1.0    1.0      1.0
1   kiran     70   2.0  2.0  2.0    2.0    2.0      2.0
2     ram     89   3.0  3.0  3.0    3.0    3.0      3.0
3  naveen     90   5.0  5.0  4.0    4.0    4.0      4.5
4  krisha     90   5.0  5.0  4.0    4.0    5.0      4.5