In [3]:
import pandas as pd 

#1. Import Pandas and read the CSV file into a DataFrame.
df = pd.read_csv("tips.csv")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
# 2. Display the first 5 rows.
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
# 3. Display the last 10 rows.
df.tail(10)

     total_bill   tip     sex smoker   day    time  size
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [6]:
# 4. Display  the first 15 rows.
df.head(15)

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4
12       15.42  1.57    Male     No  Sun  Dinner     2
13       18.43  3.00    Male     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2

In [9]:
# 5. Find the number of rows and columns.
df.shape

(244, 7)

In [10]:
# 6. Display the column names.
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [11]:
 #7. Check the shape of the DataFrame.
df.ndim

2

In [12]:
# 8. Display the data types of all columns.
df.dtypes

total_bill    float64
tip           float64
sex               str
smoker            str
day               str
time              str
size            int64
dtype: object

In [13]:
# 9. Display the DataFrame information using info().
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

In [14]:
#10. Generate a statistical summary using describe().
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [15]:
#11. Check whether the DataFrame contains missing values.
df.isnull()

     total_bill    tip    sex  smoker    day   time   size
0         False  False  False   False  False  False  False
1         False  False  False   False  False  False  False
2         False  False  False   False  False  False  False
3         False  False  False   False  False  False  False
4         False  False  False   False  False  False  False
..          ...    ...    ...     ...    ...    ...    ...
239       False  False  False   False  False  False  False
240       False  False  False   False  False  False  False
241       False  False  False   False  False  False  False
242       False  False  False   False  False  False  False
243       False  False  False   False  False  False  False

[244 rows x 7 columns]

In [18]:
# 12. Count the number of duplicate rows.
df.duplicated().sum()

np.int64(1)

In [19]:
# 13. Display only the total_bill column.
df["total_bill"]

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [20]:
# 14. Display only the tip column.
df["tip"]

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [22]:
 #15. Select the total_bill and tip columns together.
df[["total_bill","tip"]]

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [26]:

#16. Display customers whose total_bill is greater than 20.
df[df["total_bill"]>20]

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
237       32.83  1.17    Male    Yes  Sat  Dinner     2
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2

[97 rows x 7 columns]

In [27]:
#17. Display customers whose tip is greater than 3.
df[df["tip"]>3]

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
219       30.14  3.09  Female    Yes  Sat  Dinner     4
221       13.42  3.48  Female    Yes  Fri   Lunch     2
232       11.61  3.39    Male     No  Sat  Dinner     2
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3

[98 rows x 7 columns]

In [28]:
#18. Display customers whose total_bill is less than 10.
df[df["total_bill"]<10]

     total_bill   tip     sex smoker   day    time  size
6          8.77  2.00    Male     No   Sun  Dinner     2
30         9.55  1.45    Male     No   Sat  Dinner     2
43         9.68  1.32    Male     No   Sun  Dinner     2
53         9.94  1.56    Male     No   Sun  Dinner     2
67         3.07  1.00  Female    Yes   Sat  Dinner     1
92         5.75  1.00  Female    Yes   Fri  Dinner     2
111        7.25  1.00  Female     No   Sat  Dinner     1
126        8.52  1.48    Male     No  Thur   Lunch     2
135        8.51  1.25  Female     No  Thur   Lunch     2
145        8.35  1.50  Female     No  Thur   Lunch     2
148        9.78  1.73    Male     No  Thur   Lunch     2
149        7.51  2.00    Male     No  Thur   Lunch     2
172        7.25  5.15    Male    Yes   Sun  Dinner     2
178        9.60  4.00  Female    Yes   Sun  Dinner     2
195        7.56  1.44    Male     No  Thur   Lunch     2
218        7.74  1.44    Male    Yes   Sat  Dinner     2
222        8.58  1.92    Male    Yes   Fri   Lunch     1

In [29]:
#19. Display all male customers.
df[df["sex"] == "Male"]

     total_bill   tip   sex smoker  day    time  size
1         10.34  1.66  Male     No  Sun  Dinner     3
2         21.01  3.50  Male     No  Sun  Dinner     3
3         23.68  3.31  Male     No  Sun  Dinner     2
5         25.29  4.71  Male     No  Sun  Dinner     4
6          8.77  2.00  Male     No  Sun  Dinner     2
..          ...   ...   ...    ...  ...     ...   ...
236       12.60  1.00  Male    Yes  Sat  Dinner     2
237       32.83  1.17  Male    Yes  Sat  Dinner     2
239       29.03  5.92  Male     No  Sat  Dinner     3
241       22.67  2.00  Male    Yes  Sat  Dinner     2
242       17.82  1.75  Male     No  Sat  Dinner     2

[157 rows x 7 columns]

In [30]:
#20. Display all female customers.
df[df["sex"]=='Female']

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
..          ...   ...     ...    ...   ...     ...   ...
226       10.09  2.00  Female    Yes   Fri   Lunch     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[87 rows x 7 columns]

In [31]:
#21. Display customers who are smokers.
df[df["smoker"]=='Yes']

     total_bill   tip     sex smoker  day    time  size
56        38.01  3.00    Male    Yes  Sat  Dinner     4
58        11.24  1.76    Male    Yes  Sat  Dinner     2
60        20.29  3.21    Male    Yes  Sat  Dinner     2
61        13.81  2.00    Male    Yes  Sat  Dinner     2
62        11.02  1.98    Male    Yes  Sat  Dinner     2
..          ...   ...     ...    ...  ...     ...   ...
234       15.53  3.00    Male    Yes  Sat  Dinner     2
236       12.60  1.00    Male    Yes  Sat  Dinner     2
237       32.83  1.17    Male    Yes  Sat  Dinner     2
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2

[93 rows x 7 columns]

In [32]:
#22. Display customers who are not smokers.
df[df["smoker"]=='No']

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
235       10.07  1.25    Male     No   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[151 rows x 7 columns]

In [34]:
#23. Display customers who visited on Sunday.
df[df["day"]=='Sun']

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
186       20.90  3.50  Female    Yes  Sun  Dinner     3
187       30.46  2.00    Male    Yes  Sun  Dinner     5
188       18.15  3.50  Female    Yes  Sun  Dinner     3
189       23.10  4.00    Male    Yes  Sun  Dinner     3
190       15.69  1.50    Male    Yes  Sun  Dinner     2

[76 rows x 7 columns]

In [35]:
#24. Display customers who visited on Saturday.
df[df["day"]=='Sat']

     total_bill   tip     sex smoker  day    time  size
19        20.65  3.35    Male     No  Sat  Dinner     3
20        17.92  4.08    Male     No  Sat  Dinner     2
21        20.29  2.75  Female     No  Sat  Dinner     2
22        15.77  2.23  Female     No  Sat  Dinner     2
23        39.42  7.58    Male     No  Sat  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2
242       17.82  1.75    Male     No  Sat  Dinner     2

[87 rows x 7 columns]

In [36]:
#25. Display customers who came for Dinner.
df[df["time"]=='Dinner']

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[176 rows x 7 columns]

In [38]:
#26. Display customers whose group size is greater than 3.
df[df["size"]>3]

     total_bill   tip     sex smoker   day    time  size
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
7         26.88  3.12    Male     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
13        18.43  3.00    Male     No   Sun  Dinner     4
23        39.42  7.58    Male     No   Sat  Dinner     4
25        17.81  2.34    Male     No   Sat  Dinner     4
31        18.35  2.50    Male     No   Sat  Dinner     4
33        20.69  2.45  Female     No   Sat  Dinner     4
44        30.40  5.60    Male     No   Sun  Dinner     4
47        32.40  6.00    Male     No   Sun  Dinner     4
52        34.81  5.20  Female     No   Sun  Dinner     4
54        25.56  4.34    Male     No   Sun  Dinner     4
56        38.01  3.00    Male    Yes   Sat  Dinner     4
59        48.27  6.73    Male     No   Sat  Dinner     4
63        18.29  3.76    Male    Yes   Sat  Dinner     4
77        27.20  4.00    Male     No  Thur   Lunch     4
85        34.83  5.17  Female     No  Thur   Lunch     4
95        40.17  4.73    Male    Yes   Fri  Dinner     4
116       29.93  5.07    Male     No   Sun  Dinner     4
119       24.08  2.92  Female     No  Thur   Lunch     4
125       29.80  4.20  Female     No  Thur   Lunch     6
141       34.30  6.70    Male     No  Thur   Lunch     6
142       41.19  5.00    Male     No  Thur   Lunch     5
143       27.05  5.00  Female     No  Thur   Lunch     6
153       24.55  2.00    Male     No   Sun  Dinner     4
154       19.77  2.00    Male     No   Sun  Dinner     4
155       29.85  5.14  Female     No   Sun  Dinner     5
156       48.17  5.00    Male     No   Sun  Dinner     6
157       25.00  3.75  Female     No   Sun  Dinner     4
159       16.49  2.00    Male     No   Sun  Dinner     4
160       21.50  3.50    Male     No   Sun  Dinner     4
167       31.71  4.50    Male     No   Sun  Dinner     4
180       34.65  3.68    Male    Yes   Sun  Dinner     4
183       23.17  6.50    Male    Yes   Sun  Dinner     4
185       20.69  5.00    Male     No   Sun  Dinner     5
187       30.46  2.00    Male    Yes   Sun  Dinner     5
197       43.11  5.00  Female    Yes  Thur   Lunch     4
204       20.53  4.00    Male    Yes  Thur   Lunch     4
207       38.73  3.00    Male    Yes   Sat  Dinner     4
211       25.89  5.16    Male    Yes   Sat  Dinner     4
212       48.33  9.00    Male     No   Sat  Dinner     4
216       28.15  3.00    Male    Yes   Sat  Dinner     5
219       30.14  3.09  Female    Yes   Sat  Dinner     4
227       20.45  3.00    Male     No   Sat  Dinner     4
230       24.01  2.00    Male    Yes   Sat  Dinner     4

In [41]:
#27. Display customers whose total_bill is greater than 20 and tip is greater than 3.
df[(df["total_bill"] > 20) & (df["tip"] > 3)]

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
212       48.33  9.00    Male     No  Sat  Dinner     4
214       28.17  6.50  Female    Yes  Sat  Dinner     3
219       30.14  3.09  Female    Yes  Sat  Dinner     4
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3

[67 rows x 7 columns]

In [42]:
#28. Display customers whose total_bill is greater than 30 or tip is greater than 5.
df[(df["total_bill"]>30) | (df["tip"]>5)]

     total_bill    tip     sex smoker   day    time  size
11        35.26   5.00  Female     No   Sun  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
39        31.27   5.00    Male     No   Sat  Dinner     3
44        30.40   5.60    Male     No   Sun  Dinner     4
47        32.40   6.00    Male     No   Sun  Dinner     4
52        34.81   5.20  Female     No   Sun  Dinner     4
56        38.01   3.00    Male    Yes   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
83        32.68   5.00    Male    Yes  Thur   Lunch     2
85        34.83   5.17  Female     No  Thur   Lunch     4
88        24.71   5.85    Male     No  Thur   Lunch     2
95        40.17   4.73    Male    Yes   Fri  Dinner     4
102       44.30   2.50  Female    Yes   Sat  Dinner     3
112       38.07   4.00    Male     No   Sun  Dinner     3
116       29.93   5.07    Male     No   Sun  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
142       41.19   5.00    Male     No  Thur   Lunch     5
155       29.85   5.14  Female     No   Sun  Dinner     5
156       48.17   5.00    Male     No   Sun  Dinner     6
167       31.71   4.50    Male     No   Sun  Dinner     4
170       50.81  10.00    Male    Yes   Sat  Dinner     3
172        7.25   5.15    Male    Yes   Sun  Dinner     2
173       31.85   3.18    Male    Yes   Sun  Dinner     2
175       32.90   3.11    Male    Yes   Sun  Dinner     2
179       34.63   3.55    Male    Yes   Sun  Dinner     2
180       34.65   3.68    Male    Yes   Sun  Dinner     4
181       23.33   5.65    Male    Yes   Sun  Dinner     2
182       45.35   3.50    Male    Yes   Sun  Dinner     3
183       23.17   6.50    Male    Yes   Sun  Dinner     4
184       40.55   3.00    Male    Yes   Sun  Dinner     2
187       30.46   2.00    Male    Yes   Sun  Dinner     5
197       43.11   5.00  Female    Yes  Thur   Lunch     4
207       38.73   3.00    Male    Yes   Sat  Dinner     4
210       30.06   2.00    Male    Yes   Sat  Dinner     3
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
219       30.14   3.09  Female    Yes   Sat  Dinner     4
237       32.83   1.17    Male    Yes   Sat  Dinner     2
238       35.83   4.67  Female     No   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3

In [43]:
#29. Display male customers who are smokers
df[(df["sex"]=='Male') & (df["smoker"]=='Yes')]

     total_bill    tip   sex smoker   day    time  size
56        38.01   3.00  Male    Yes   Sat  Dinner     4
58        11.24   1.76  Male    Yes   Sat  Dinner     2
60        20.29   3.21  Male    Yes   Sat  Dinner     2
61        13.81   2.00  Male    Yes   Sat  Dinner     2
62        11.02   1.98  Male    Yes   Sat  Dinner     2
63        18.29   3.76  Male    Yes   Sat  Dinner     4
69        15.01   2.09  Male    Yes   Sat  Dinner     2
76        17.92   3.08  Male    Yes   Sat  Dinner     2
80        19.44   3.00  Male    Yes  Thur   Lunch     2
83        32.68   5.00  Male    Yes  Thur   Lunch     2
90        28.97   3.00  Male    Yes   Fri  Dinner     2
95        40.17   4.73  Male    Yes   Fri  Dinner     4
96        27.28   4.00  Male    Yes   Fri  Dinner     2
97        12.03   1.50  Male    Yes   Fri  Dinner     2
98        21.01   3.00  Male    Yes   Fri  Dinner     2
105       15.36   1.64  Male    Yes   Sat  Dinner     2
106       20.49   4.06  Male    Yes   Sat  Dinner     2
107       25.21   4.29  Male    Yes   Sat  Dinner     2
138       16.00   2.00  Male    Yes  Thur   Lunch     2
170       50.81  10.00  Male    Yes   Sat  Dinner     3
171       15.81   3.16  Male    Yes   Sat  Dinner     2
172        7.25   5.15  Male    Yes   Sun  Dinner     2
173       31.85   3.18  Male    Yes   Sun  Dinner     2
174       16.82   4.00  Male    Yes   Sun  Dinner     2
175       32.90   3.11  Male    Yes   Sun  Dinner     2
176       17.89   2.00  Male    Yes   Sun  Dinner     2
177       14.48   2.00  Male    Yes   Sun  Dinner     2
179       34.63   3.55  Male    Yes   Sun  Dinner     2
180       34.65   3.68  Male    Yes   Sun  Dinner     4
181       23.33   5.65  Male    Yes   Sun  Dinner     2
182       45.35   3.50  Male    Yes   Sun  Dinner     3
183       23.17   6.50  Male    Yes   Sun  Dinner     4
184       40.55   3.00  Male    Yes   Sun  Dinner     2
187       30.46   2.00  Male    Yes   Sun  Dinner     5
189       23.10   4.00  Male    Yes   Sun  Dinner     3
190       15.69   1.50  Male    Yes   Sun  Dinner     2
192       28.44   2.56  Male    Yes  Thur   Lunch     2
193       15.48   2.02  Male    Yes  Thur   Lunch     2
194       16.58   4.00  Male    Yes  Thur   Lunch     2
196       10.34   2.00  Male    Yes  Thur   Lunch     2
199       13.51   2.00  Male    Yes  Thur   Lunch     2
200       18.71   4.00  Male    Yes  Thur   Lunch     3
204       20.53   4.00  Male    Yes  Thur   Lunch     4
206       26.59   3.41  Male    Yes   Sat  Dinner     3
207       38.73   3.00  Male    Yes   Sat  Dinner     4
208       24.27   2.03  Male    Yes   Sat  Dinner     2
210       30.06   2.00  Male    Yes   Sat  Dinner     3
211       25.89   5.16  Male    Yes   Sat  Dinner     4
216       28.15   3.00  Male    Yes   Sat  Dinner     5
217       11.59   1.50  Male    Yes   Sat  Dinner     2
218        7.74   1.44  Male    Yes   Sat  Dinner     2
220       12.16   2.20  Male    Yes   Fri   Lunch     2
222        8.58   1.92  Male    Yes   Fri   Lunch     1
224       13.42   1.58  Male    Yes   Fri   Lunch     2
230       24.01   2.00  Male    Yes   Sat  Dinner     4
231       15.69   3.00  Male    Yes   Sat  Dinner     3
234       15.53   3.00  Male    Yes   Sat  Dinner     2
236       12.60   1.00  Male    Yes   Sat  Dinner     2
237       32.83   1.17  Male    Yes   Sat  Dinner     2
241       22.67   2.00  Male    Yes   Sat  Dinner     2

In [44]:
#30. Display customers who visited on Friday or Saturday.
df[(df["day"]=='Fri') | (df["day"]=='Sat')]

     total_bill   tip     sex smoker  day    time  size
19        20.65  3.35    Male     No  Sat  Dinner     3
20        17.92  4.08    Male     No  Sat  Dinner     2
21        20.29  2.75  Female     No  Sat  Dinner     2
22        15.77  2.23  Female     No  Sat  Dinner     2
23        39.42  7.58    Male     No  Sat  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2
242       17.82  1.75    Male     No  Sat  Dinner     2

[106 rows x 7 columns]