In [ ]:
'''Merge:-> if we want to combine two table
    Syntax:->   newvarName=pd.merge(leftTable,rightTable,ON=column,how=Type of join)-> by default inner join

    -> 
    
    '''

In [3]:
import pandas as pd

name=["A","B","C","D","E"]
id=[1,2,3,4,5]

tabel1={"NAME":name,"ID":id}

df1=pd.DataFrame(tabel1)
df1

  NAME  ID
0    A   1
1    B   2
2    C   3
3    D   4
4    E   5

In [7]:
df2=pd.DataFrame({"ID":[2,3,4,6,7],"MARKS":[45,90,66,35,75]})
df2

   ID  MARKS
0   2     45
1   3     90
2   4     66
3   6     35
4   7     75

In [8]:
res=pd.merge(df1,df2,on="ID")
res

  NAME  ID  MARKS
0    B   2     45
1    C   3     90
2    D   4     66

In [10]:
res1=pd.merge(df1,df2,on="ID", how="inner")
res1

  NAME  ID  MARKS
0    B   2     45
1    C   3     90
2    D   4     66

In [12]:
res2=pd.merge(df1,df2,on="ID", how="right")
res2

  NAME  ID  MARKS
0    B   2     45
1    C   3     90
2    D   4     66
3  NaN   6     35
4  NaN   7     75

In [13]:
res3=pd.merge(df1,df2,on="ID", how="left")
res3

  NAME  ID  MARKS
0    A   1    NaN
1    B   2   45.0
2    C   3   90.0
3    D   4   66.0
4    E   5    NaN

In [14]:
res4=pd.merge(df1,df2,on="ID",how="outer")
res4

  NAME  ID  MARKS
0    A   1    NaN
1    B   2   45.0
2    C   3   90.0
3    D   4   66.0
4    E   5    NaN
5  NaN   6   35.0
6  NaN   7   75.0

In [19]:
t1=pd.DataFrame({"ID":[2,3,4,6,7], "name": ["A", "B", "C", "D", "E"]})
t2 = pd.DataFrame({"MARKS":[45,90,66,35,75],"Rank": ["*", 2, 3, 4, 5]})

In [27]:
result=pd.merge(t1,t2,left_on="ID",right_on="MARKS",how="outer")
result

    ID name  MARKS Rank
0  2.0    A    NaN  NaN
1  3.0    B    NaN  NaN
2  4.0    C    NaN  NaN
3  6.0    D    NaN  NaN
4  7.0    E    NaN  NaN
5  NaN  NaN   35.0    4
6  NaN  NaN   45.0    *
7  NaN  NaN   66.0    3
8  NaN  NaN   75.0    5
9  NaN  NaN   90.0    2

In [ ]:
res=pd.concat([t1,t2],axis=1) #1-> col ,0-> row
res

   ID name  MARKS Rank
0   2    A     45    *
1   3    B     90    2
2   4    C     66    3
3   6    D     35    4
4   7    E     75    5

In [31]:
t1.join(t2)

   ID name  MARKS Rank
0   2    A     45    *
1   3    B     90    2
2   4    C     66    3
3   6    D     35    4
4   7    E     75    5