In [1]:
import pandas as pd

data={
    "name":["A","B","C","D"],
    "age":[23,45,66,78],
    "sal":[1000,2000,3000,4000],
    "department":["HR","Analysis","HR","IT"]
}
df=pd.DataFrame(data)
df

  name  age   sal department
0    A   23  1000         HR
1    B   45  2000   Analysis
2    C   66  3000         HR
3    D   78  4000         IT

In [2]:
df.groupby("department")

In [4]:
df.groupby("department")["sal"].value_counts()

department  sal
Analysis    2000    1
HR          1000    1
            3000    1
IT          4000    1
Name: count, dtype: int64

In [5]:
df.groupby("department")["sal"].sum()

department
Analysis    2000
HR          4000
IT          4000
Name: sal, dtype: int64

In [6]:
df.groupby("department")["sal"].mean()

department
Analysis    2000.0
HR          2000.0
IT          4000.0
Name: sal, dtype: float64

In [7]:
df.groupby("department")["sal"].count()

department
Analysis    1
HR          2
IT          1
Name: sal, dtype: int64

In [9]:
df.groupby("department")["sal"].agg(["min","sum","max","count"])

             min   sum   max  count
department
Analysis    2000  2000  2000      1
HR          1000  4000  3000      2
IT          4000  4000  4000      1

In [12]:
#age=60 and working in Hr

df[(df["age"]==60) | (df["department"]=="HR")]

  name  age   sal department
0    A   23  1000         HR
2    C   66  3000         HR