In [1]:
import pandas as pd

df=pd.read_csv("college_students.csv")

df

,Student_ID,Student_Name,Age,Department,City,Favourite_Food,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery,Excuse,Placement_Status
0,101.0,aJAY SLEEPY,20.0,Python,Bengaluru,dosa,45.0,25.0,0.0,2.0,bus late,not ready
1,102.0,bINDU BIRYANI,21.0,Data Science,Mysuru,BIRYANI,88.0,91.0,5000.0,100.0,no excuse,PLACED
2,103.0,CHANDRU CHAI,19.0,Python,Hubballi,ChAi,72.0,64.0,1500.0,18.0,need chai,interview soon
3,104.0,dIVYA DRAMA,20.0,Testing,Bengaluru,Pizza,95.0,98.0,0.0,76.0,family function,Placed
4,105.0,Eshwar Einstein,22.0,Data Science,Mangaluru,pani puri,81.0,86.0,8000.0,55.0,WiFi issue,PLACED
5,106.0,fATIMA FOODIE,21.0,Testing,Mysuru,Biryani,NaN,73.0,2500.0,9.0,sleeping,training
6,107.0,GOPI GAMER,20.0,Python,Bengaluru,noodles,67.0,55.0,3000.0,1.0,gaming all night,not ready
7,108.0,harry homeworkless,19.0,Web Dev,Pune,Pizza,32.0,18.0,0.0,4.0,alarm failed,not ready
8,109.0,INDU INSTA,22.0,Data Science,Chennai,ice cream,91.0,89.0,4000.0,99.0,reel making,placed
9,110.0,jAGGU JOKER,23.0,Testing,Bengaluru,DOSA,58.0,42.0,1000.0,13.0,traffic,training
10,111.0,KAVYA KANNADA,20.0,Python,Mysuru,masala dosa,84.0,78.0,0.0,67.0,festival,Placed
11,112.0,lOKI LATECOMER,21.0,Web Dev,Pune,Burger,40.0,NaN,2000.0,5.0,overslept,interview soon
12,113.0,MADHU MEMER,NaN,Testing,Hubballi,biryani,76.0,68.0,3500.0,28.0,forgot timetable,training
13,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
14,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
'''1.shape
2.size
3.ndim
4.columns
5.index
6.dtypes
7.values
8.axes
9.T
10.empty
11.attrs'''

In [2]:
df.shape

(16, 12)

In [3]:
df.size

192

In [5]:
df.ndim

2

In [6]:
df.columns

Index(['Student_ID', 'Student_Name', 'Age', 'Department', 'City',
       'Favourite_Food', 'Attendance_Percent', 'Marks', 'Part_Time_Salary',
       'Phone_Battery', 'Excuse', 'Placement_Status'],
      dtype='str')

In [7]:
df.index

RangeIndex(start=0, stop=16, step=1)

In [8]:
df.dtypes

Student_ID            float64
Student_Name              str
Age                   float64
Department                str
City                      str
Favourite_Food            str
Attendance_Percent    float64
Marks                 float64
Part_Time_Salary      float64
Phone_Battery         float64
Excuse                    str
Placement_Status          str
dtype: object

In [9]:
df.values

array([[101.0, '  aJAY SLEEPY  ', 20.0, 'Python', 'Bengaluru', 'dosa',
        45.0, 25.0, 0.0, 2.0, '  bus late ', 'not ready'],
       [102.0, 'bINDU BIRYANI', 21.0, 'Data Science', 'Mysuru',
        'BIRYANI', 88.0, 91.0, 5000.0, 100.0, 'no excuse', 'PLACED'],
       [103.0, 'CHANDRU CHAI', 19.0, 'Python', 'Hubballi', 'ChAi', 72.0,
        64.0, 1500.0, 18.0, 'need chai', 'interview soon'],
       [104.0, 'dIVYA DRAMA', 20.0, 'Testing', 'Bengaluru', 'Pizza',
        95.0, 98.0, 0.0, 76.0, 'family function', 'Placed'],
       [105.0, 'Eshwar Einstein', 22.0, 'Data Science', 'Mangaluru',
        'pani puri', 81.0, 86.0, 8000.0, 55.0, 'WiFi issue', 'PLACED'],
       [106.0, 'fATIMA FOODIE', 21.0, 'Testing', 'Mysuru', 'Biryani',
        nan, 73.0, 2500.0, 9.0, 'sleeping', 'training'],
       [107.0, 'GOPI GAMER', 20.0, 'Python', 'Bengaluru', 'noodles',
        67.0, 55.0, 3000.0, 1.0, 'gaming all night', 'not ready'],
       [108.0, 'harry homeworkless', 19.0, 'Web Dev', 'Pune', 'Pizza',
        32.0, 18.0, 0.0, 4.0, 'alarm failed', 'not ready'],
       [109.0, 'INDU INSTA', 22.0, 'Data Science', 'Chennai',
        'ice cream', 91.0, 89.0, 4000.0, 99.0, 'reel making', 'placed'],
       [110.0, 'jAGGU JOKER', 23.0, 'Testing', 'Bengaluru', 'DOSA', 58.0,
        42.0, 1000.0, 13.0, 'traffic', 'training'],
       [111.0, 'KAVYA KANNADA', 20.0, 'Python', 'Mysuru', 'masala dosa',
        84.0, 78.0, 0.0, 67.0, 'festival', 'Placed'],
       [112.0, 'lOKI LATECOMER', 21.0, 'Web Dev', 'Pune', 'Burger', 40.0,
        nan, 2000.0, 5.0, 'overslept', 'interview soon'],
       [113.0, 'MADHU MEMER', nan, 'Testing', 'Hubballi', 'biryani',
        76.0, 68.0, 3500.0, 28.0, 'forgot timetable', 'training'],
       [114.0, 'NANDU NAP KING', 22.0, 'Python', 'Chennai', 'noodles',
        62.0, 39.0, 500.0, 3.0, 'one more nap', 'not ready'],
       [114.0, 'NANDU NAP KING', 22.0, 'Python', 'Chennai', 'noodles',
        62.0, 39.0, 500.0, 3.0, 'one more nap', 'not ready'],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]],
      dtype=object)

In [10]:
df.axes

[RangeIndex(start=0, stop=16, step=1),
 Index(['Student_ID', 'Student_Name', 'Age', 'Department', 'City',
        'Favourite_Food', 'Attendance_Percent', 'Marks', 'Part_Time_Salary',
        'Phone_Battery', 'Excuse', 'Placement_Status'],
       dtype='str')]

In [11]:
df.T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
Student_ID,101.0,102.0,103.0,104.0,105.0,106.0,107.0,108.0,109.0,110.0,111.0,112.0,113.0,114.0,114.0,NaN
Student_Name,aJAY SLEEPY,bINDU BIRYANI,CHANDRU CHAI,dIVYA DRAMA,Eshwar Einstein,fATIMA FOODIE,GOPI GAMER,harry homeworkless,INDU INSTA,jAGGU JOKER,KAVYA KANNADA,lOKI LATECOMER,MADHU MEMER,NANDU NAP KING,NANDU NAP KING,NaN
Age,20.0,21.0,19.0,20.0,22.0,21.0,20.0,19.0,22.0,23.0,20.0,21.0,NaN,22.0,22.0,NaN
Department,Python,Data Science,Python,Testing,Data Science,Testing,Python,Web Dev,Data Science,Testing,Python,Web Dev,Testing,Python,Python,NaN
City,Bengaluru,Mysuru,Hubballi,Bengaluru,Mangaluru,Mysuru,Bengaluru,Pune,Chennai,Bengaluru,Mysuru,Pune,Hubballi,Chennai,Chennai,NaN
Favourite_Food,dosa,BIRYANI,ChAi,Pizza,pani puri,Biryani,noodles,Pizza,ice cream,DOSA,masala dosa,Burger,biryani,noodles,noodles,NaN
Attendance_Percent,45.0,88.0,72.0,95.0,81.0,NaN,67.0,32.0,91.0,58.0,84.0,40.0,76.0,62.0,62.0,NaN
Marks,25.0,91.0,64.0,98.0,86.0,73.0,55.0,18.0,89.0,42.0,78.0,NaN,68.0,39.0,39.0,NaN
Part_Time_Salary,0.0,5000.0,1500.0,0.0,8000.0,2500.0,3000.0,0.0,4000.0,1000.0,0.0,2000.0,3500.0,500.0,500.0,NaN
Phone_Battery,2.0,100.0,18.0,76.0,55.0,9.0,1.0,4.0,99.0,13.0,67.0,5.0,28.0,3.0,3.0,NaN
Excuse,bus late,no excuse,need chai,family function,WiFi issue,sleeping,gaming all night,alarm failed,reel making,traffic,festival,overslept,forgot timetable,one more nap,one more nap,NaN
Placement_Status,not ready,PLACED,interview soon,Placed,PLACED,training,not ready,not ready,placed,training,Placed,interview soon,training,not ready,not ready,NaN

In [12]:
df.empty

False

In [13]:
df.attrs

{}

In [ ]:
'''methods List
1.head()
2.tail()
3.sample()
http://4.info()
5.describe()
6.value_counts()
7.nunique()
8.unique()
9.memory_usage()
10.select_dtypes()'''

In [14]:
df.head()

,Student_ID,Student_Name,Age,Department,City,Favourite_Food,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery,Excuse,Placement_Status
0,101.0,aJAY SLEEPY,20.0,Python,Bengaluru,dosa,45.0,25.0,0.0,2.0,bus late,not ready
1,102.0,bINDU BIRYANI,21.0,Data Science,Mysuru,BIRYANI,88.0,91.0,5000.0,100.0,no excuse,PLACED
2,103.0,CHANDRU CHAI,19.0,Python,Hubballi,ChAi,72.0,64.0,1500.0,18.0,need chai,interview soon
3,104.0,dIVYA DRAMA,20.0,Testing,Bengaluru,Pizza,95.0,98.0,0.0,76.0,family function,Placed
4,105.0,Eshwar Einstein,22.0,Data Science,Mangaluru,pani puri,81.0,86.0,8000.0,55.0,WiFi issue,PLACED

In [15]:
df.tail()

,Student_ID,Student_Name,Age,Department,City,Favourite_Food,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery,Excuse,Placement_Status
11,112.0,lOKI LATECOMER,21.0,Web Dev,Pune,Burger,40.0,NaN,2000.0,5.0,overslept,interview soon
12,113.0,MADHU MEMER,NaN,Testing,Hubballi,biryani,76.0,68.0,3500.0,28.0,forgot timetable,training
13,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
14,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df.sample()

,Student_ID,Student_Name,Age,Department,City,Favourite_Food,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery,Excuse,Placement_Status
3,104.0,dIVYA DRAMA,20.0,Testing,Bengaluru,Pizza,95.0,98.0,0.0,76.0,family function,Placed

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_ID          15 non-null     float64
 1   Student_Name        15 non-null     str
 2   Age                 14 non-null     float64
 3   Department          15 non-null     str
 4   City                15 non-null     str
 5   Favourite_Food      15 non-null     str
 6   Attendance_Percent  14 non-null     float64
 7   Marks               14 non-null     float64
 8   Part_Time_Salary    15 non-null     float64
 9   Phone_Battery       15 non-null     float64
 10  Excuse              15 non-null     str
 11  Placement_Status    15 non-null     str
dtypes: float64(6), str(6)
memory usage: 1.6 KB

In [18]:
df.describe()

,Student_ID,Age,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery
count,15.000000,14.000000,14.000000,14.000000,15.000000,15.000000
mean,107.933333,20.857143,68.071429,61.785714,2100.000000,32.200000
std,4.366539,1.231456,19.503311,25.825386,2300.621034,36.801009
min,101.000000,19.000000,32.000000,18.000000,0.000000,1.000000
25%,104.500000,20.000000,59.000000,39.750000,250.000000,3.500000
50%,108.000000,21.000000,69.500000,66.000000,1500.000000,13.000000
75%,111.500000,22.000000,83.250000,84.000000,3250.000000,61.000000
max,114.000000,23.000000,95.000000,98.000000,8000.000000,100.000000

In [19]:
df.value_counts()

Student_ID  Student_Name        Age   Department    City       Favourite_Food  Attendance_Percent  Marks  Part_Time_Salary  Phone_Battery  Excuse            Placement_Status
114.0       NANDU NAP KING      22.0  Python        Chennai    noodles         62.0                39.0   500.0             3.0            one more nap      not ready           2
101.0         aJAY SLEEPY       20.0  Python        Bengaluru  dosa            45.0                25.0   0.0               2.0              bus late        not ready           1
102.0       bINDU BIRYANI       21.0  Data Science  Mysuru     BIRYANI         88.0                91.0   5000.0            100.0          no excuse         PLACED              1
103.0       CHANDRU CHAI        19.0  Python        Hubballi   ChAi            72.0                64.0   1500.0            18.0           need chai         interview soon      1
104.0       dIVYA DRAMA         20.0  Testing       Bengaluru  Pizza           95.0                98.0   0.0               76.0           family function   Placed              1
105.0       Eshwar Einstein     22.0  Data Science  Mangaluru  pani puri       81.0                86.0   8000.0            55.0           WiFi issue        PLACED              1
107.0       GOPI GAMER          20.0  Python        Bengaluru  noodles         67.0                55.0   3000.0            1.0            gaming all night  not ready           1
108.0       harry homeworkless  19.0  Web Dev       Pune       Pizza           32.0                18.0   0.0               4.0            alarm failed      not ready           1
109.0       INDU INSTA          22.0  Data Science  Chennai    ice cream       91.0                89.0   4000.0            99.0           reel making       placed              1
110.0       jAGGU JOKER         23.0  Testing       Bengaluru  DOSA            58.0                42.0   1000.0            13.0           traffic           training            1
111.0       KAVYA KANNADA       20.0  Python        Mysuru     masala dosa     84.0                78.0   0.0               67.0           festival          Placed              1
Name: count, dtype: int64

In [20]:
df.nunique()

Student_ID            14
Student_Name          14
Age                    5
Department             4
City                   6
Favourite_Food        12
Attendance_Percent    13
Marks                 13
Part_Time_Salary      11
Phone_Battery         14
Excuse                14
Placement_Status       6
dtype: int64

In [22]:
df.memory_usage()

Index                 132
Student_ID            128
Student_Name          128
Age                   128
Department            128
City                  128
Favourite_Food        128
Attendance_Percent    128
Marks                 128
Part_Time_Salary      128
Phone_Battery         128
Excuse                128
Placement_Status      128
dtype: int64

In [24]:
df.select_dtypes(float)

,Student_ID,Age,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery
0,101.0,20.0,45.0,25.0,0.0,2.0
1,102.0,21.0,88.0,91.0,5000.0,100.0
2,103.0,19.0,72.0,64.0,1500.0,18.0
3,104.0,20.0,95.0,98.0,0.0,76.0
4,105.0,22.0,81.0,86.0,8000.0,55.0
5,106.0,21.0,NaN,73.0,2500.0,9.0
6,107.0,20.0,67.0,55.0,3000.0,1.0
7,108.0,19.0,32.0,18.0,0.0,4.0
8,109.0,22.0,91.0,89.0,4000.0,99.0
9,110.0,23.0,58.0,42.0,1000.0,13.0
10,111.0,20.0,84.0,78.0,0.0,67.0
11,112.0,21.0,40.0,NaN,2000.0,5.0
12,113.0,NaN,76.0,68.0,3500.0,28.0
13,114.0,22.0,62.0,39.0,500.0,3.0
14,114.0,22.0,62.0,39.0,500.0,3.0
15,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
'''Selecting and filtering data
1.loc[]
2.iloc[]
3.query()
4.isin()
5.between()
6.where()
7.mask()'''

In [25]:
df.loc[5]

Student_ID                    106.0
Student_Name          fATIMA FOODIE
Age                            21.0
Department                  Testing
City                         Mysuru
Favourite_Food              Biryani
Attendance_Percent              NaN
Marks                          73.0
Part_Time_Salary             2500.0
Phone_Battery                   9.0
Excuse                     sleeping
Placement_Status           training
Name: 5, dtype: object

In [26]:
df.loc[5,["Age"]]

Age    21.0
Name: 5, dtype: float64

In [27]:
df.loc[5:7,["Age"]]

    Age
5  21.0
6  20.0
7  19.0

In [28]:
df.loc[5:7,["Age","Student_Name"]]

    Age        Student_Name
5  21.0       fATIMA FOODIE
6  20.0          GOPI GAMER
7  19.0  harry homeworkless

In [30]:
df.iloc[1]

Student_ID                    102.0
Student_Name          bINDU BIRYANI
Age                            21.0
Department             Data Science
City                         Mysuru
Favourite_Food              BIRYANI
Attendance_Percent             88.0
Marks                          91.0
Part_Time_Salary             5000.0
Phone_Battery                 100.0
Excuse                    no excuse
Placement_Status             PLACED
Name: 1, dtype: object

In [31]:
df.iloc[0]

Student_ID                      101.0
Student_Name            aJAY SLEEPY
Age                              20.0
Department                     Python
City                        Bengaluru
Favourite_Food                   dosa
Attendance_Percent               45.0
Marks                            25.0
Part_Time_Salary                  0.0
Phone_Battery                     2.0
Excuse                      bus late
Placement_Status            not ready
Name: 0, dtype: object

In [32]:
df.query("Age>20")

,Student_ID,Student_Name,Age,Department,City,Favourite_Food,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery,Excuse,Placement_Status
1,102.0,bINDU BIRYANI,21.0,Data Science,Mysuru,BIRYANI,88.0,91.0,5000.0,100.0,no excuse,PLACED
4,105.0,Eshwar Einstein,22.0,Data Science,Mangaluru,pani puri,81.0,86.0,8000.0,55.0,WiFi issue,PLACED
5,106.0,fATIMA FOODIE,21.0,Testing,Mysuru,Biryani,NaN,73.0,2500.0,9.0,sleeping,training
8,109.0,INDU INSTA,22.0,Data Science,Chennai,ice cream,91.0,89.0,4000.0,99.0,reel making,placed
9,110.0,jAGGU JOKER,23.0,Testing,Bengaluru,DOSA,58.0,42.0,1000.0,13.0,traffic,training
11,112.0,lOKI LATECOMER,21.0,Web Dev,Pune,Burger,40.0,NaN,2000.0,5.0,overslept,interview soon
13,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
14,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready

In [39]:
df.isin([114])

,Student_ID,Student_Name,Age,Department,City,Favourite_Food,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery,Excuse,Placement_Status
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False
13,True,False,False,False,False,False,False,False,False,False,False,False
14,True,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False

In [41]:
df.where(df["Age"]>20)

,Student_ID,Student_Name,Age,Department,City,Favourite_Food,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery,Excuse,Placement_Status
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,102.0,bINDU BIRYANI,21.0,Data Science,Mysuru,BIRYANI,88.0,91.0,5000.0,100.0,no excuse,PLACED
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,105.0,Eshwar Einstein,22.0,Data Science,Mangaluru,pani puri,81.0,86.0,8000.0,55.0,WiFi issue,PLACED
5,106.0,fATIMA FOODIE,21.0,Testing,Mysuru,Biryani,NaN,73.0,2500.0,9.0,sleeping,training
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,109.0,INDU INSTA,22.0,Data Science,Chennai,ice cream,91.0,89.0,4000.0,99.0,reel making,placed
9,110.0,jAGGU JOKER,23.0,Testing,Bengaluru,DOSA,58.0,42.0,1000.0,13.0,traffic,training
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,112.0,lOKI LATECOMER,21.0,Web Dev,Pune,Burger,40.0,NaN,2000.0,5.0,overslept,interview soon
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
14,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
df.mask(df["Age"]<20)

,Student_ID,Student_Name,Age,Department,City,Favourite_Food,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery,Excuse,Placement_Status
0,101.0,aJAY SLEEPY,20.0,Python,Bengaluru,dosa,45.0,25.0,0.0,2.0,bus late,not ready
1,102.0,bINDU BIRYANI,21.0,Data Science,Mysuru,BIRYANI,88.0,91.0,5000.0,100.0,no excuse,PLACED
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,104.0,dIVYA DRAMA,20.0,Testing,Bengaluru,Pizza,95.0,98.0,0.0,76.0,family function,Placed
4,105.0,Eshwar Einstein,22.0,Data Science,Mangaluru,pani puri,81.0,86.0,8000.0,55.0,WiFi issue,PLACED
5,106.0,fATIMA FOODIE,21.0,Testing,Mysuru,Biryani,NaN,73.0,2500.0,9.0,sleeping,training
6,107.0,GOPI GAMER,20.0,Python,Bengaluru,noodles,67.0,55.0,3000.0,1.0,gaming all night,not ready
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,109.0,INDU INSTA,22.0,Data Science,Chennai,ice cream,91.0,89.0,4000.0,99.0,reel making,placed
9,110.0,jAGGU JOKER,23.0,Testing,Bengaluru,DOSA,58.0,42.0,1000.0,13.0,traffic,training
10,111.0,KAVYA KANNADA,20.0,Python,Mysuru,masala dosa,84.0,78.0,0.0,67.0,festival,Placed
11,112.0,lOKI LATECOMER,21.0,Web Dev,Pune,Burger,40.0,NaN,2000.0,5.0,overslept,interview soon
12,113.0,MADHU MEMER,NaN,Testing,Hubballi,biryani,76.0,68.0,3500.0,28.0,forgot timetable,training
13,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
14,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
'''Adding, removing and modifying data
1.drop()
2.rename()
3.insert()
4.assign()
5.pop()
6.astype()'''

In [43]:
df.drop(15)

,Student_ID,Student_Name,Age,Department,City,Favourite_Food,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery,Excuse,Placement_Status
0,101.0,aJAY SLEEPY,20.0,Python,Bengaluru,dosa,45.0,25.0,0.0,2.0,bus late,not ready
1,102.0,bINDU BIRYANI,21.0,Data Science,Mysuru,BIRYANI,88.0,91.0,5000.0,100.0,no excuse,PLACED
2,103.0,CHANDRU CHAI,19.0,Python,Hubballi,ChAi,72.0,64.0,1500.0,18.0,need chai,interview soon
3,104.0,dIVYA DRAMA,20.0,Testing,Bengaluru,Pizza,95.0,98.0,0.0,76.0,family function,Placed
4,105.0,Eshwar Einstein,22.0,Data Science,Mangaluru,pani puri,81.0,86.0,8000.0,55.0,WiFi issue,PLACED
5,106.0,fATIMA FOODIE,21.0,Testing,Mysuru,Biryani,NaN,73.0,2500.0,9.0,sleeping,training
6,107.0,GOPI GAMER,20.0,Python,Bengaluru,noodles,67.0,55.0,3000.0,1.0,gaming all night,not ready
7,108.0,harry homeworkless,19.0,Web Dev,Pune,Pizza,32.0,18.0,0.0,4.0,alarm failed,not ready
8,109.0,INDU INSTA,22.0,Data Science,Chennai,ice cream,91.0,89.0,4000.0,99.0,reel making,placed
9,110.0,jAGGU JOKER,23.0,Testing,Bengaluru,DOSA,58.0,42.0,1000.0,13.0,traffic,training
10,111.0,KAVYA KANNADA,20.0,Python,Mysuru,masala dosa,84.0,78.0,0.0,67.0,festival,Placed
11,112.0,lOKI LATECOMER,21.0,Web Dev,Pune,Burger,40.0,NaN,2000.0,5.0,overslept,interview soon
12,113.0,MADHU MEMER,NaN,Testing,Hubballi,biryani,76.0,68.0,3500.0,28.0,forgot timetable,training
13,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
14,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready

In [48]:
df = df.rename(columns={"Age": "StudentAge"})
df

,Student_ID,Student_Name,StudentAge,Department,City,Favourite_Food,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery,Excuse,Placement_Status
0,101.0,aJAY SLEEPY,20.0,Python,Bengaluru,dosa,45.0,25.0,0.0,2.0,bus late,not ready
1,102.0,bINDU BIRYANI,21.0,Data Science,Mysuru,BIRYANI,88.0,91.0,5000.0,100.0,no excuse,PLACED
2,103.0,CHANDRU CHAI,19.0,Python,Hubballi,ChAi,72.0,64.0,1500.0,18.0,need chai,interview soon
3,104.0,dIVYA DRAMA,20.0,Testing,Bengaluru,Pizza,95.0,98.0,0.0,76.0,family function,Placed
4,105.0,Eshwar Einstein,22.0,Data Science,Mangaluru,pani puri,81.0,86.0,8000.0,55.0,WiFi issue,PLACED
5,106.0,fATIMA FOODIE,21.0,Testing,Mysuru,Biryani,NaN,73.0,2500.0,9.0,sleeping,training
6,107.0,GOPI GAMER,20.0,Python,Bengaluru,noodles,67.0,55.0,3000.0,1.0,gaming all night,not ready
7,108.0,harry homeworkless,19.0,Web Dev,Pune,Pizza,32.0,18.0,0.0,4.0,alarm failed,not ready
8,109.0,INDU INSTA,22.0,Data Science,Chennai,ice cream,91.0,89.0,4000.0,99.0,reel making,placed
9,110.0,jAGGU JOKER,23.0,Testing,Bengaluru,DOSA,58.0,42.0,1000.0,13.0,traffic,training
10,111.0,KAVYA KANNADA,20.0,Python,Mysuru,masala dosa,84.0,78.0,0.0,67.0,festival,Placed
11,112.0,lOKI LATECOMER,21.0,Web Dev,Pune,Burger,40.0,NaN,2000.0,5.0,overslept,interview soon
12,113.0,MADHU MEMER,NaN,Testing,Hubballi,biryani,76.0,68.0,3500.0,28.0,forgot timetable,training
13,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
14,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
df.insert(4,"YOP","NaN")
df

,Student_ID,Student_Name,StudentAge,Department,YOP,PhoneNumber,City,Favourite_Food,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery,Excuse,Placement_Status
0,101.0,aJAY SLEEPY,20.0,Python,NaN,NaN,Bengaluru,dosa,45.0,25.0,0.0,2.0,bus late,not ready
1,102.0,bINDU BIRYANI,21.0,Data Science,NaN,NaN,Mysuru,BIRYANI,88.0,91.0,5000.0,100.0,no excuse,PLACED
2,103.0,CHANDRU CHAI,19.0,Python,NaN,NaN,Hubballi,ChAi,72.0,64.0,1500.0,18.0,need chai,interview soon
3,104.0,dIVYA DRAMA,20.0,Testing,NaN,NaN,Bengaluru,Pizza,95.0,98.0,0.0,76.0,family function,Placed
4,105.0,Eshwar Einstein,22.0,Data Science,NaN,NaN,Mangaluru,pani puri,81.0,86.0,8000.0,55.0,WiFi issue,PLACED
5,106.0,fATIMA FOODIE,21.0,Testing,NaN,NaN,Mysuru,Biryani,NaN,73.0,2500.0,9.0,sleeping,training
6,107.0,GOPI GAMER,20.0,Python,NaN,NaN,Bengaluru,noodles,67.0,55.0,3000.0,1.0,gaming all night,not ready
7,108.0,harry homeworkless,19.0,Web Dev,NaN,NaN,Pune,Pizza,32.0,18.0,0.0,4.0,alarm failed,not ready
8,109.0,INDU INSTA,22.0,Data Science,NaN,NaN,Chennai,ice cream,91.0,89.0,4000.0,99.0,reel making,placed
9,110.0,jAGGU JOKER,23.0,Testing,NaN,NaN,Bengaluru,DOSA,58.0,42.0,1000.0,13.0,traffic,training
10,111.0,KAVYA KANNADA,20.0,Python,NaN,NaN,Mysuru,masala dosa,84.0,78.0,0.0,67.0,festival,Placed
11,112.0,lOKI LATECOMER,21.0,Web Dev,NaN,NaN,Pune,Burger,40.0,NaN,2000.0,5.0,overslept,interview soon
12,113.0,MADHU MEMER,NaN,Testing,NaN,NaN,Hubballi,biryani,76.0,68.0,3500.0,28.0,forgot timetable,training
13,114.0,NANDU NAP KING,22.0,Python,NaN,NaN,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
14,114.0,NANDU NAP KING,22.0,Python,NaN,NaN,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
df.assign(Campus=["ABC","ABC","ABC","ABC","ABC","ABC","ABC","NaN","ABC","ABC","ABC","ABC","ABC","ABC","NaN","NaN"])

,Student_ID,Student_Name,StudentAge,Department,YOP,PhoneNumber,City,Favourite_Food,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery,Excuse,Placement_Status,Campus
0,101.0,aJAY SLEEPY,20.0,Python,NaN,NaN,Bengaluru,dosa,45.0,25.0,0.0,2.0,bus late,not ready,ABC
1,102.0,bINDU BIRYANI,21.0,Data Science,NaN,NaN,Mysuru,BIRYANI,88.0,91.0,5000.0,100.0,no excuse,PLACED,ABC
2,103.0,CHANDRU CHAI,19.0,Python,NaN,NaN,Hubballi,ChAi,72.0,64.0,1500.0,18.0,need chai,interview soon,ABC
3,104.0,dIVYA DRAMA,20.0,Testing,NaN,NaN,Bengaluru,Pizza,95.0,98.0,0.0,76.0,family function,Placed,ABC
4,105.0,Eshwar Einstein,22.0,Data Science,NaN,NaN,Mangaluru,pani puri,81.0,86.0,8000.0,55.0,WiFi issue,PLACED,ABC
5,106.0,fATIMA FOODIE,21.0,Testing,NaN,NaN,Mysuru,Biryani,NaN,73.0,2500.0,9.0,sleeping,training,ABC
6,107.0,GOPI GAMER,20.0,Python,NaN,NaN,Bengaluru,noodles,67.0,55.0,3000.0,1.0,gaming all night,not ready,ABC
7,108.0,harry homeworkless,19.0,Web Dev,NaN,NaN,Pune,Pizza,32.0,18.0,0.0,4.0,alarm failed,not ready,NaN
8,109.0,INDU INSTA,22.0,Data Science,NaN,NaN,Chennai,ice cream,91.0,89.0,4000.0,99.0,reel making,placed,ABC
9,110.0,jAGGU JOKER,23.0,Testing,NaN,NaN,Bengaluru,DOSA,58.0,42.0,1000.0,13.0,traffic,training,ABC
10,111.0,KAVYA KANNADA,20.0,Python,NaN,NaN,Mysuru,masala dosa,84.0,78.0,0.0,67.0,festival,Placed,ABC
11,112.0,lOKI LATECOMER,21.0,Web Dev,NaN,NaN,Pune,Burger,40.0,NaN,2000.0,5.0,overslept,interview soon,ABC
12,113.0,MADHU MEMER,NaN,Testing,NaN,NaN,Hubballi,biryani,76.0,68.0,3500.0,28.0,forgot timetable,training,ABC
13,114.0,NANDU NAP KING,22.0,Python,NaN,NaN,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready,ABC
14,114.0,NANDU NAP KING,22.0,Python,NaN,NaN,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
df.pop("YOP")

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
15    NaN
Name: YOP, dtype: str

In [64]:
'''"""
Cleaning data

1.isna()
2.notna()
3.dropna()
4.fillna()
5.ffill()
6.bfill()
7.replace()
8.duplicated()
9.drop_duplicates()
"""'''

'"""\nCleaning data\n\n1.isna()\n2.notna()\n3.dropna()\n4.fillna()\n5.ffill()\n6.bfill()\n7.replace()\n8.duplicated()\n9.drop_duplicates()\n"""'

In [65]:
df.isna()

,Student_ID,Student_Name,StudentAge,Department,PhoneNumber,City,Favourite_Food,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery,Excuse,Placement_Status
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,True,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,True,False,False,False,False
12,False,False,True,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False
15,True,True,True,True,False,True,True,True,True,True,True,True,True

In [66]:
df.notna()

,Student_ID,Student_Name,StudentAge,Department,PhoneNumber,City,Favourite_Food,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery,Excuse,Placement_Status
0,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True
5,True,True,True,True,True,True,True,False,True,True,True,True,True
6,True,True,True,True,True,True,True,True,True,True,True,True,True
7,True,True,True,True,True,True,True,True,True,True,True,True,True
8,True,True,True,True,True,True,True,True,True,True,True,True,True
9,True,True,True,True,True,True,True,True,True,True,True,True,True
10,True,True,True,True,True,True,True,True,True,True,True,True,True
11,True,True,True,True,True,True,True,True,False,True,True,True,True
12,True,True,False,True,True,True,True,True,True,True,True,True,True
13,True,True,True,True,True,True,True,True,True,True,True,True,True
14,True,True,True,True,True,True,True,True,True,True,True,True,True
15,False,False,False,False,True,False,False,False,False,False,False,False,False

In [67]:
df.dropna()

,Student_ID,Student_Name,StudentAge,Department,PhoneNumber,City,Favourite_Food,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery,Excuse,Placement_Status
0,101.0,aJAY SLEEPY,20.0,Python,NaN,Bengaluru,dosa,45.0,25.0,0.0,2.0,bus late,not ready
1,102.0,bINDU BIRYANI,21.0,Data Science,NaN,Mysuru,BIRYANI,88.0,91.0,5000.0,100.0,no excuse,PLACED
2,103.0,CHANDRU CHAI,19.0,Python,NaN,Hubballi,ChAi,72.0,64.0,1500.0,18.0,need chai,interview soon
3,104.0,dIVYA DRAMA,20.0,Testing,NaN,Bengaluru,Pizza,95.0,98.0,0.0,76.0,family function,Placed
4,105.0,Eshwar Einstein,22.0,Data Science,NaN,Mangaluru,pani puri,81.0,86.0,8000.0,55.0,WiFi issue,PLACED
6,107.0,GOPI GAMER,20.0,Python,NaN,Bengaluru,noodles,67.0,55.0,3000.0,1.0,gaming all night,not ready
7,108.0,harry homeworkless,19.0,Web Dev,NaN,Pune,Pizza,32.0,18.0,0.0,4.0,alarm failed,not ready
8,109.0,INDU INSTA,22.0,Data Science,NaN,Chennai,ice cream,91.0,89.0,4000.0,99.0,reel making,placed
9,110.0,jAGGU JOKER,23.0,Testing,NaN,Bengaluru,DOSA,58.0,42.0,1000.0,13.0,traffic,training
10,111.0,KAVYA KANNADA,20.0,Python,NaN,Mysuru,masala dosa,84.0,78.0,0.0,67.0,festival,Placed
13,114.0,NANDU NAP KING,22.0,Python,NaN,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
14,114.0,NANDU NAP KING,22.0,Python,NaN,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready

In [68]:
df.fillna("*")

,Student_ID,Student_Name,StudentAge,Department,PhoneNumber,City,Favourite_Food,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery,Excuse,Placement_Status
0,101.0,aJAY SLEEPY,20.0,Python,NaN,Bengaluru,dosa,45.0,25.0,0.0,2.0,bus late,not ready
1,102.0,bINDU BIRYANI,21.0,Data Science,NaN,Mysuru,BIRYANI,88.0,91.0,5000.0,100.0,no excuse,PLACED
2,103.0,CHANDRU CHAI,19.0,Python,NaN,Hubballi,ChAi,72.0,64.0,1500.0,18.0,need chai,interview soon
3,104.0,dIVYA DRAMA,20.0,Testing,NaN,Bengaluru,Pizza,95.0,98.0,0.0,76.0,family function,Placed
4,105.0,Eshwar Einstein,22.0,Data Science,NaN,Mangaluru,pani puri,81.0,86.0,8000.0,55.0,WiFi issue,PLACED
5,106.0,fATIMA FOODIE,21.0,Testing,NaN,Mysuru,Biryani,*,73.0,2500.0,9.0,sleeping,training
6,107.0,GOPI GAMER,20.0,Python,NaN,Bengaluru,noodles,67.0,55.0,3000.0,1.0,gaming all night,not ready
7,108.0,harry homeworkless,19.0,Web Dev,NaN,Pune,Pizza,32.0,18.0,0.0,4.0,alarm failed,not ready
8,109.0,INDU INSTA,22.0,Data Science,NaN,Chennai,ice cream,91.0,89.0,4000.0,99.0,reel making,placed
9,110.0,jAGGU JOKER,23.0,Testing,NaN,Bengaluru,DOSA,58.0,42.0,1000.0,13.0,traffic,training
10,111.0,KAVYA KANNADA,20.0,Python,NaN,Mysuru,masala dosa,84.0,78.0,0.0,67.0,festival,Placed
11,112.0,lOKI LATECOMER,21.0,Web Dev,NaN,Pune,Burger,40.0,*,2000.0,5.0,overslept,interview soon
12,113.0,MADHU MEMER,*,Testing,NaN,Hubballi,biryani,76.0,68.0,3500.0,28.0,forgot timetable,training
13,114.0,NANDU NAP KING,22.0,Python,NaN,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
14,114.0,NANDU NAP KING,22.0,Python,NaN,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
15,*,*,*,*,NaN,*,*,*,*,*,*,*,*

In [73]:
df.ffill()

,Student_ID,Student_Name,StudentAge,Department,City,Favourite_Food,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery,Excuse,Placement_Status
0,101.0,aJAY SLEEPY,20.0,Python,Bengaluru,dosa,45.0,25.0,0.0,2.0,bus late,not ready
1,102.0,bINDU BIRYANI,21.0,Data Science,Mysuru,BIRYANI,88.0,91.0,5000.0,100.0,no excuse,PLACED
2,103.0,CHANDRU CHAI,19.0,Python,Hubballi,ChAi,72.0,64.0,1500.0,18.0,need chai,interview soon
3,104.0,dIVYA DRAMA,20.0,Testing,Bengaluru,Pizza,95.0,98.0,0.0,76.0,family function,Placed
4,105.0,Eshwar Einstein,22.0,Data Science,Mangaluru,pani puri,81.0,86.0,8000.0,55.0,WiFi issue,PLACED
5,106.0,fATIMA FOODIE,21.0,Testing,Mysuru,Biryani,81.0,73.0,2500.0,9.0,sleeping,training
6,107.0,GOPI GAMER,20.0,Python,Bengaluru,noodles,67.0,55.0,3000.0,1.0,gaming all night,not ready
7,108.0,harry homeworkless,19.0,Web Dev,Pune,Pizza,32.0,18.0,0.0,4.0,alarm failed,not ready
8,109.0,INDU INSTA,22.0,Data Science,Chennai,ice cream,91.0,89.0,4000.0,99.0,reel making,placed
9,110.0,jAGGU JOKER,23.0,Testing,Bengaluru,DOSA,58.0,42.0,1000.0,13.0,traffic,training
10,111.0,KAVYA KANNADA,20.0,Python,Mysuru,masala dosa,84.0,78.0,0.0,67.0,festival,Placed
11,112.0,lOKI LATECOMER,21.0,Web Dev,Pune,Burger,40.0,78.0,2000.0,5.0,overslept,interview soon
12,113.0,MADHU MEMER,21.0,Testing,Hubballi,biryani,76.0,68.0,3500.0,28.0,forgot timetable,training
13,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
14,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
15,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready

In [74]:
df.bfill()

,Student_ID,Student_Name,StudentAge,Department,City,Favourite_Food,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery,Excuse,Placement_Status
0,101.0,aJAY SLEEPY,20.0,Python,Bengaluru,dosa,45.0,25.0,0.0,2.0,bus late,not ready
1,102.0,bINDU BIRYANI,21.0,Data Science,Mysuru,BIRYANI,88.0,91.0,5000.0,100.0,no excuse,PLACED
2,103.0,CHANDRU CHAI,19.0,Python,Hubballi,ChAi,72.0,64.0,1500.0,18.0,need chai,interview soon
3,104.0,dIVYA DRAMA,20.0,Testing,Bengaluru,Pizza,95.0,98.0,0.0,76.0,family function,Placed
4,105.0,Eshwar Einstein,22.0,Data Science,Mangaluru,pani puri,81.0,86.0,8000.0,55.0,WiFi issue,PLACED
5,106.0,fATIMA FOODIE,21.0,Testing,Mysuru,Biryani,67.0,73.0,2500.0,9.0,sleeping,training
6,107.0,GOPI GAMER,20.0,Python,Bengaluru,noodles,67.0,55.0,3000.0,1.0,gaming all night,not ready
7,108.0,harry homeworkless,19.0,Web Dev,Pune,Pizza,32.0,18.0,0.0,4.0,alarm failed,not ready
8,109.0,INDU INSTA,22.0,Data Science,Chennai,ice cream,91.0,89.0,4000.0,99.0,reel making,placed
9,110.0,jAGGU JOKER,23.0,Testing,Bengaluru,DOSA,58.0,42.0,1000.0,13.0,traffic,training
10,111.0,KAVYA KANNADA,20.0,Python,Mysuru,masala dosa,84.0,78.0,0.0,67.0,festival,Placed
11,112.0,lOKI LATECOMER,21.0,Web Dev,Pune,Burger,40.0,68.0,2000.0,5.0,overslept,interview soon
12,113.0,MADHU MEMER,22.0,Testing,Hubballi,biryani,76.0,68.0,3500.0,28.0,forgot timetable,training
13,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
14,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [82]:
df["City"]=df["City"].replace("Pune","USA")
df

,Student_ID,Student_Name,StudentAge,Department,City,Favourite_Food,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery,Excuse,Placement_Status
0,101.0,aJAY SLEEPY,20.0,Python,Bengaluru,dosa,45.0,25.0,0.0,2.0,bus late,not ready
1,102.0,bINDU BIRYANI,21.0,Data Science,Mysuru,BIRYANI,88.0,91.0,5000.0,100.0,no excuse,PLACED
2,103.0,CHANDRU CHAI,19.0,Python,Hubballi,ChAi,72.0,64.0,1500.0,18.0,need chai,interview soon
3,104.0,dIVYA DRAMA,20.0,Testing,Bengaluru,Pizza,95.0,98.0,0.0,76.0,family function,Placed
4,105.0,Eshwar Einstein,22.0,Data Science,Mangaluru,pani puri,81.0,86.0,8000.0,55.0,WiFi issue,PLACED
5,106.0,fATIMA FOODIE,21.0,Testing,Mysuru,Biryani,NaN,73.0,2500.0,9.0,sleeping,training
6,107.0,GOPI GAMER,20.0,Python,Bengaluru,noodles,67.0,55.0,3000.0,1.0,gaming all night,not ready
7,108.0,harry homeworkless,19.0,Web Dev,USA,Pizza,32.0,18.0,0.0,4.0,alarm failed,not ready
8,109.0,INDU INSTA,22.0,Data Science,Chennai,ice cream,91.0,89.0,4000.0,99.0,reel making,placed
9,110.0,jAGGU JOKER,23.0,Testing,Bengaluru,DOSA,58.0,42.0,1000.0,13.0,traffic,training
10,111.0,KAVYA KANNADA,20.0,Python,Mysuru,masala dosa,84.0,78.0,0.0,67.0,festival,Placed
11,112.0,lOKI LATECOMER,21.0,Web Dev,USA,Burger,40.0,NaN,2000.0,5.0,overslept,interview soon
12,113.0,MADHU MEMER,NaN,Testing,Hubballi,biryani,76.0,68.0,3500.0,28.0,forgot timetable,training
13,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
14,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
15,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14     True
15    False
dtype: bool

In [86]:
df.drop_duplicates()

,Student_ID,Student_Name,StudentAge,Department,City,Favourite_Food,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery,Excuse,Placement_Status
0,101.0,aJAY SLEEPY,20.0,Python,Bengaluru,dosa,45.0,25.0,0.0,2.0,bus late,not ready
1,102.0,bINDU BIRYANI,21.0,Data Science,Mysuru,BIRYANI,88.0,91.0,5000.0,100.0,no excuse,PLACED
2,103.0,CHANDRU CHAI,19.0,Python,Hubballi,ChAi,72.0,64.0,1500.0,18.0,need chai,interview soon
3,104.0,dIVYA DRAMA,20.0,Testing,Bengaluru,Pizza,95.0,98.0,0.0,76.0,family function,Placed
4,105.0,Eshwar Einstein,22.0,Data Science,Mangaluru,pani puri,81.0,86.0,8000.0,55.0,WiFi issue,PLACED
5,106.0,fATIMA FOODIE,21.0,Testing,Mysuru,Biryani,NaN,73.0,2500.0,9.0,sleeping,training
6,107.0,GOPI GAMER,20.0,Python,Bengaluru,noodles,67.0,55.0,3000.0,1.0,gaming all night,not ready
7,108.0,harry homeworkless,19.0,Web Dev,USA,Pizza,32.0,18.0,0.0,4.0,alarm failed,not ready
8,109.0,INDU INSTA,22.0,Data Science,Chennai,ice cream,91.0,89.0,4000.0,99.0,reel making,placed
9,110.0,jAGGU JOKER,23.0,Testing,Bengaluru,DOSA,58.0,42.0,1000.0,13.0,traffic,training
10,111.0,KAVYA KANNADA,20.0,Python,Mysuru,masala dosa,84.0,78.0,0.0,67.0,festival,Placed
11,112.0,lOKI LATECOMER,21.0,Web Dev,USA,Burger,40.0,NaN,2000.0,5.0,overslept,interview soon
12,113.0,MADHU MEMER,NaN,Testing,Hubballi,biryani,76.0,68.0,3500.0,28.0,forgot timetable,training
13,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
15,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
'''Case conversion methods
--------------------------------
str.lower()
str.upper()
str.title()
str.capitalize()
str.casefold()
str.swapcase()

'''

In [87]:
df.columns.str.lower()

Index(['student_id', 'student_name', 'studentage', 'department', 'city',
       'favourite_food', 'attendance_percent', 'marks', 'part_time_salary',
       'phone_battery', 'excuse', 'placement_status'],
      dtype='str')

In [88]:
df["Favourite_Food"].str.lower()

0            dosa
1         biryani
2            chai
3           pizza
4       pani puri
5         biryani
6         noodles
7           pizza
8       ice cream
9            dosa
10    masala dosa
11         burger
12        biryani
13        noodles
14        noodles
15            NaN
Name: Favourite_Food, dtype: str

In [90]:
df["Department"].str.upper()

0           PYTHON
1     DATA SCIENCE
2           PYTHON
3          TESTING
4     DATA SCIENCE
5          TESTING
6           PYTHON
7          WEB DEV
8     DATA SCIENCE
9          TESTING
10          PYTHON
11         WEB DEV
12         TESTING
13          PYTHON
14          PYTHON
15             NaN
Name: Department, dtype: str

In [91]:
df["Student_Name"].str.title()

0          Ajay Sleepy
1          Bindu Biryani
2           Chandru Chai
3            Divya Drama
4        Eshwar Einstein
5          Fatima Foodie
6             Gopi Gamer
7     Harry Homeworkless
8             Indu Insta
9            Jaggu Joker
10         Kavya Kannada
11        Loki Latecomer
12           Madhu Memer
13        Nandu Nap King
14        Nandu Nap King
15                   NaN
Name: Student_Name, dtype: str

In [92]:
df["Student_Name"].str.capitalize()

0          ajay sleepy
1          Bindu biryani
2           Chandru chai
3            Divya drama
4        Eshwar einstein
5          Fatima foodie
6             Gopi gamer
7     Harry homeworkless
8             Indu insta
9            Jaggu joker
10         Kavya kannada
11        Loki latecomer
12           Madhu memer
13        Nandu nap king
14        Nandu nap king
15                   NaN
Name: Student_Name, dtype: str

In [93]:
df["Student_Name"].str.casefold()

0          ajay sleepy
1          bindu biryani
2           chandru chai
3            divya drama
4        eshwar einstein
5          fatima foodie
6             gopi gamer
7     harry homeworkless
8             indu insta
9            jaggu joker
10         kavya kannada
11        loki latecomer
12           madhu memer
13        nandu nap king
14        nandu nap king
15                   NaN
Name: Student_Name, dtype: str

In [94]:
df["Student_Name"].str.swapcase()

0          Ajay sleepy
1          Bindu biryani
2           chandru chai
3            Divya drama
4        eSHWAR eINSTEIN
5          Fatima foodie
6             gopi gamer
7     HARRY HOMEWORKLESS
8             indu insta
9            Jaggu joker
10         kavya kannada
11        Loki latecomer
12           madhu memer
13        nandu nap king
14        nandu nap king
15                   NaN
Name: Student_Name, dtype: str

In [ ]:
'''Removing spaces and characters
---------------------------------

str.strip()
str.lstrip()
str.rstrip()
str.removeprefix()
str.removesuffix()'''

In [95]:
df["Student_Name"].str.strip()

0            aJAY SLEEPY
1          bINDU BIRYANI
2           CHANDRU CHAI
3            dIVYA DRAMA
4        Eshwar Einstein
5          fATIMA FOODIE
6             GOPI GAMER
7     harry homeworkless
8             INDU INSTA
9            jAGGU JOKER
10         KAVYA KANNADA
11        lOKI LATECOMER
12           MADHU MEMER
13        NANDU NAP KING
14        NANDU NAP KING
15                   NaN
Name: Student_Name, dtype: str

In [97]:
df["Student_Name"].str.rstrip()

0            aJAY SLEEPY
1          bINDU BIRYANI
2           CHANDRU CHAI
3            dIVYA DRAMA
4        Eshwar Einstein
5          fATIMA FOODIE
6             GOPI GAMER
7     harry homeworkless
8             INDU INSTA
9            jAGGU JOKER
10         KAVYA KANNADA
11        lOKI LATECOMER
12           MADHU MEMER
13        NANDU NAP KING
14        NANDU NAP KING
15                   NaN
Name: Student_Name, dtype: str

In [98]:
df["Student_Name"].str.lstrip()

0          aJAY SLEEPY
1          bINDU BIRYANI
2           CHANDRU CHAI
3            dIVYA DRAMA
4        Eshwar Einstein
5          fATIMA FOODIE
6             GOPI GAMER
7     harry homeworkless
8             INDU INSTA
9            jAGGU JOKER
10         KAVYA KANNADA
11        lOKI LATECOMER
12           MADHU MEMER
13        NANDU NAP KING
14        NANDU NAP KING
15                   NaN
Name: Student_Name, dtype: str

In [102]:
df["Placement_Status"].str.removeprefix("not")

0              ready
1             PLACED
2     interview soon
3             Placed
4             PLACED
5           training
6              ready
7              ready
8             placed
9           training
10            Placed
11    interview soon
12          training
13             ready
14             ready
15               NaN
Name: Placement_Status, dtype: str

In [105]:
df["Placement_Status"].str.removesuffix("soon")

0      not ready
1         PLACED
2     interview
3         Placed
4         PLACED
5       training
6      not ready
7      not ready
8         placed
9       training
10        Placed
11    interview
12      training
13     not ready
14     not ready
15           NaN
Name: Placement_Status, dtype: str

In [ ]:
'''Searching and checking strings
---------------------------------

str.contains()
str.startswith()
str.endswith()
str.find()
str.rfind()
str.index()
str.rindex()
str.count()

'''

In [110]:
df["Department"].str.startswith("Data")

0     False
1      True
2     False
3     False
4      True
5     False
6     False
7     False
8      True
9     False
10    False
11    False
12    False
13    False
14    False
15    False
Name: Department, dtype: bool

In [114]:
df["Department"].str.endswith("Dev")

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15    False
Name: Department, dtype: bool

In [115]:
df

,Student_ID,Student_Name,StudentAge,Department,City,Favourite_Food,Attendance_Percent,Marks,Part_Time_Salary,Phone_Battery,Excuse,Placement_Status
0,101.0,aJAY SLEEPY,20.0,Python,Bengaluru,dosa,45.0,25.0,0.0,2.0,bus late,not ready
1,102.0,bINDU BIRYANI,21.0,Data Science,Mysuru,BIRYANI,88.0,91.0,5000.0,100.0,no excuse,PLACED
2,103.0,CHANDRU CHAI,19.0,Python,Hubballi,ChAi,72.0,64.0,1500.0,18.0,need chai,interview soon
3,104.0,dIVYA DRAMA,20.0,Testing,Bengaluru,Pizza,95.0,98.0,0.0,76.0,family function,Placed
4,105.0,Eshwar Einstein,22.0,Data Science,Mangaluru,pani puri,81.0,86.0,8000.0,55.0,WiFi issue,PLACED
5,106.0,fATIMA FOODIE,21.0,Testing,Mysuru,Biryani,NaN,73.0,2500.0,9.0,sleeping,training
6,107.0,GOPI GAMER,20.0,Python,Bengaluru,noodles,67.0,55.0,3000.0,1.0,gaming all night,not ready
7,108.0,harry homeworkless,19.0,Web Dev,USA,Pizza,32.0,18.0,0.0,4.0,alarm failed,not ready
8,109.0,INDU INSTA,22.0,Data Science,Chennai,ice cream,91.0,89.0,4000.0,99.0,reel making,placed
9,110.0,jAGGU JOKER,23.0,Testing,Bengaluru,DOSA,58.0,42.0,1000.0,13.0,traffic,training
10,111.0,KAVYA KANNADA,20.0,Python,Mysuru,masala dosa,84.0,78.0,0.0,67.0,festival,Placed
11,112.0,lOKI LATECOMER,21.0,Web Dev,USA,Burger,40.0,NaN,2000.0,5.0,overslept,interview soon
12,113.0,MADHU MEMER,NaN,Testing,Hubballi,biryani,76.0,68.0,3500.0,28.0,forgot timetable,training
13,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
14,114.0,NANDU NAP KING,22.0,Python,Chennai,noodles,62.0,39.0,500.0,3.0,one more nap,not ready
15,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [116]:
df["Department"].str.find("Python")

0     0.0
1    -1.0
2     0.0
3    -1.0
4    -1.0
5    -1.0
6     0.0
7    -1.0
8    -1.0
9    -1.0
10    0.0
11   -1.0
12   -1.0
13    0.0
14    0.0
15    NaN
Name: Department, dtype: float64